export { default as Home } from './Home/Home';
export { default as Detail } from './Products/Detail';
export { default as Products } from './Products/Products';
export { default as Cart } from './Cart/Cart';
export { default as Contact } from './Contact/Contact';
export { default as NotFound } from './NotFound/NotFound';
export { default as SignIn } from './SignIn/SignIn';
export { default as SignOut } from './SignOut/SignOut';
export { default as SignUp } from './SignUp/SignUp';
